build: Add shell scripts verification using shellcheck
See https://github.com/koalaman/shellcheck/wiki

Signed-off-by: Alexey Gladkov <gladkov.alexey@gmail.com>

diff --git a/features/luks/data/lib/uevent/handlers/070-luks b/features/luks/data/lib/uevent/handlers/070-luks
--- a/features/luks/data/lib/uevent/handlers/070-luks
+++ b/features/luks/data/lib/uevent/handlers/070-luks
@@ -47,7 +47,7 @@ findkey() {
 	[ -f /etc/luks.keys ] ||
 		return 2
 
-	while IFS='	' read path keydev luksdev; do
+	while IFS='	' read -r path keydev luksdev; do
 		if [ -n "$luksdev" ]; then
 			get_dev "$luksdev" ||
 				continue
@@ -63,7 +63,7 @@ findkey() {
 		fi
 
 		if [ ! -f "$prefix/$path" ]; then
-			printf "ERROR(luks): $path: keyfile not found.\n" >&2
+			printf "ERROR(luks): %s: keyfile not found.\n" "$path" >&2
 			return 1
 		fi
 
