add-module: ignore missing module patterns too when --optional is passed

diff --git a/tools/add-module b/tools/add-module
--- a/tools/add-module
+++ b/tools/add-module
@@ -41,8 +41,10 @@ for n; do
 		[ -f "$workdir/modules" ] ||
 			find "$kernel_modules_dir" -type f -a \( -name '*.ko' -o -name '*.ko.*' \) >"$workdir/modules"
 
-		grep -E -e "$n" "$workdir/modules" >"$workdir/pattern.modules" ||
-			fatal "Unable to handle pattern: $n"
+		if ! grep -E -e "$n" "$workdir/modules" >"$workdir/pattern.modules"; then
+			[ -n "$ignore_missing" ] ||
+				fatal "Unable to handle pattern: $n"
+		fi
 
 		while read -r m; do
 			add_module "$m"
